from django.contrib import admin
from django.urls import path
from . import views
from django.views.generic.base import RedirectView

admin.site.site_header = "Login to Student Peeps"
admin.site.site_title = "Dashboard"
admin.site.index_title = "Welcome to Student Peeps Dashboard"

urlpatterns = [
    path('', views.Home.as_view(), name="Home"),
    path('category/<slug:category_id>/', views.CategoryPageView.as_view(), name='CategoryPage'),
    path('ourstory/', views.OurStory.as_view(), name="OurStory"),
    path('verification-message/',
         views.VerificationMessage.as_view(), name="Verificationmsg"),
    path('google-verification-message/',
         views.GoogleVerifyMessage.as_view(), name="GoogleVerificationmsg"),
    path('upload-message/', views.UploadMessage.as_view(), name="Uploadmsg"),
    path('google-verified/', views.GoogleVerification.as_view(), name="GoogleVerification"),
    path('contactus/', views.ContactUs.as_view(), name="ContactUs"),
    path('faq/', views.FAQ.as_view(), name="Faq"),
    path('privacypolicy/', views.Privacy.as_view(), name="PrivacyPolicy"),
    path('request-your-fav-brand/', views.Favorite.as_view(), name="Favroiute"),
    path('course-application/', views.Course.as_view(), name="Course"),
    path('resource/', views.Tools.as_view(), name="Resource"),
    path('subscribe', views.SubscribeView.as_view(), name="SubscribeView"),
    path('unsubscribe', views.UnSubscribeView.as_view(), name="UnSubscribeView"),
    path('community/', views.Community.as_view(), name="Community"),
    path('id-verification-message/',
         views.IdVerificationMessage.as_view(), name="IdVerificationMessage"),


    # Redirects for old URLs to new ones
    path('all/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('tech/', RedirectView.as_view(url='/category/tech/', permanent=True)),
    path('foodsanddrinks/', RedirectView.as_view(url='/category/food_drink/', permanent=True)),
    path('travel/', RedirectView.as_view(url='/category/travel/', permanent=True)),
    path('healthandbeauty/', RedirectView.as_view(url='/category/health_beauty/', permanent=True)),
    path('edtech/', RedirectView.as_view(url='/category/education/', permanent=True)),
    path('booksandstationary/', RedirectView.as_view(url='/category/books_stationary/', permanent=True)),
    path('homeandutilities/', RedirectView.as_view(url='/category/home_utilities/', permanent=True)),
    path('fashion/', RedirectView.as_view(url='/category/fashion/', permanent=True)),
    path('exclusive/', RedirectView.as_view(url='/category/exclusive/', permanent=True)),
    path('nonexclusive/', RedirectView.as_view(url='/category/exclusive/', permanent=True)),
    path('indigo/', RedirectView.as_view(url='/offer/indigo/spxindigo10/', permanent=True)),
    path('microsoft/', RedirectView.as_view(url='/offer/microsoft/spxmicrosoft365/', permanent=True)),
    path('spotify/', RedirectView.as_view(url='/offer/spotify/spxspotify50/', permanent=True)),
    path('notion/', RedirectView.as_view(url='/offer/notion/spxnotionfree/', permanent=True)),
    path('github/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('samsung/', RedirectView.as_view(url='/offer/samsung/spxsamsung30/', permanent=True)),
    path('adobe/', RedirectView.as_view(url='/offer/adobe/spxadobe65/', permanent=True)),
    path('apple/', RedirectView.as_view(url='/offer/apple/spxapple10/', permanent=True)),
    path('applemusic/', RedirectView.as_view(url='/offer/apple-music/spxapplemusic50/', permanent=True)),
    path('amazonprime/', RedirectView.as_view(url='/offer/amazon-prime/spxprime50/', permanent=True)),
    path('ytpremium/', RedirectView.as_view(url='/offer/youtube/spxyoutube40/', permanent=True)),
    path('oneplus/', RedirectView.as_view(url='/offer/oneplus/spxoneplus1500/', permanent=True)),
    path('wix/', RedirectView.as_view(url='/offer/wix/spxwix50/', permanent=True)),
    path('gofirst/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('easemytrip/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('vistara/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('lufthansa/', RedirectView.as_view(url='/offer/lufthansa/spxlufthansa10/', permanent=True)),
    path('spicejet/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('nestaway/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('whole-truth-food/', RedirectView.as_view(url='/offer/the-whole-truth-food/spxwtf25/', permanent=True)),
    path('student-discount-whole-truth-food/', RedirectView.as_view(url='/offer/the-whole-truth-food/spxwtf25/', permanent=True)),
    path('avni-by-giva/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-avni/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('naagin/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-naagin/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('pee-safe/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-pee-safe/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('propshop/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-propshop/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('to-be-honest/', RedirectView.as_view(url='/offer/to-be-honest/spxtbh15/', permanent=True)),
    path('student-discount-to-be-honest/', RedirectView.as_view(url='/offer/to-be-honest/spxtbh15/', permanent=True)),
    path('bitclass/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-bitclass/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('sattviko/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-sattviko/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('rapido/', RedirectView.as_view(url='/offer/rapido/spxrapido50/', permanent=True)),
    path('student-discount-rapido/', RedirectView.as_view(url='/offer/rapido/spxrapido50/', permanent=True)),
    path('the-womans-company/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-the-womans-company/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('ptal/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-ptal/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('bookchor/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-bookchor/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('bewakoof/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-bewakoof/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('inchpaper/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-inchpaper/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('udemy/', RedirectView.as_view(url='/offer/udemy/spxudemy100/', permanent=True)),
    path('student-discount-udemy/', RedirectView.as_view(url='/offer/udemy/spxudemy100/', permanent=True)),
    path('ragecoffee/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-ragecoffee/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('myntra/', RedirectView.as_view(url='/offer/myntra/spxmyntra300/', permanent=True)),
    path('student-discount-myntra/', RedirectView.as_view(url='/offer/myntra/spxmyntra300/', permanent=True)),
    path('beardo/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-beardo/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('pharmeasy/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('student-discount-pharmeasy/', RedirectView.as_view(url='/category/all/', permanent=True)),
    path('lenovo-flat-5000-off/', RedirectView.as_view(url='/offer/lenovo/spxlenovo5000/', permanent=True)),
    path('student-discount-lenovo-flat-5000-off/', RedirectView.as_view(url='/offer/lenovo/spxlenovo5000/', permanent=True)),
    path('lenovo-flat-2000-off/', RedirectView.as_view(url='/offer/lenovo/spxlenovo2000/', permanent=True)),
    path('student-discount-lenovo-flat-2000-off/', RedirectView.as_view(url='/offer/lenovo/spxlenovo2000/', permanent=True)),
    path('etihad-10-percent-off/', RedirectView.as_view(url='/offer/etihad/spxetihad10/', permanent=True)),
    path('etihad-5-percent-off/', RedirectView.as_view(url='/offer/etihad/spxetihad5/', permanent=True)),
    path('free-two-night-stay-with-etihad/', RedirectView.as_view(url='/offer/etihad/spxetihadcomp/', permanent=True)),
    path('dailyobjects/', RedirectView.as_view(url='/offer/dailyobjects/spxdailyobjects15/', permanent=True)),
    path('student-discount-dailyobjects/', RedirectView.as_view(url='/offer/dailyobjects/spxdailyobjects15/', permanent=True)),
]

