"""
Django settings for studentpeeps project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
from django.contrib.messages import constants as messages
from pathlib import Path
from decouple import config
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['studentpeeps.club', '139.59.79.183', 'www.studentpeeps.club', 'localhost', '127.0.0.1', '*']

# Application definition
INSTALLED_APPS = [
    'account',
    'accounts_v2',
    'main',
    'brands_v2',
    'utilities',
    'giftcard',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'storages',
    'django_summernote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'account.middlewares.MiddlewareToVerify',
]

ROOT_URLCONF = 'studentpeeps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'brands_v2.context_processors.search_offers',
                'brands_v2.context_processors.categories',
                'giftcard.context_processors.cart_count',
            ],
        },
    },
]

WSGI_APPLICATION = 'studentpeeps.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

#SMTP Configuration
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'email-smtp.ap-south-1.amazonaws.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'AKIA4LBWP2D7CCXP75EW'
# EMAIL_HOST_PASSWORD = 'BMn72G7Xl916/GWk15DL7Is4kHPC3g0GQDrV9vH3M1s9'
# DEFAULT_FROM_EMAIL = 'user@studentpeeps.club'

#SMTP Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('ZOHO_SMTP_HOST')
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = config('ZOHO_EMAIL_USERNAME')
EMAIL_HOST_PASSWORD = config('ZOHO_EMAIL_PASSWORD')
DEFAULT_FROM_EMAIL = config('ZOHO_EMAIL_USERNAME')
# EMAIL_ACTIVE_FIELD = 'is_active'

MESSAGE_TAGS = \
    {
        messages.ERROR: 'danger',
        messages.SUCCESS: 'success',
    }

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_SAVE_EVERY_REQUEST = True

AUTHENTICATION_BACKENDS = (
    'accounts_v2.backends.PhoneBackend', 
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
)

SOCIAL_AUTH_URL_NAMESPACE = 'social'

# Local System
# SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config('SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_LOCAL')
# SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config('SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_LOCAL')

# Production
SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = config(
    'SOCIAL_AUTH_GOOGLE_OAUTH2_KEY_PRODUCTION')
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = config(
    'SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET_PRODUCTION')

LOGIN_REDIRECT_URL = '/google-auth/'

# CELERY STUFF
CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Celery Configuration Options
CELERY_TIMEZONE = "Asia/Kolkata"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Twilio SMS Service
TWILIO_ACCOUNT_SID=config('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN=config('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER=config('TWILIO_PHONE_NUMBER')

#Fast2Sms Cred
FAST2SMS_ACCESS_KEY_ID = config('FAST2SMS_ACCESS_KEY_ID')

# AWS Creds
AWS_ACCESS_KEY_ID_EMAIL=config('AWS_ACCESS_KEY')
AWS_SECRET_ACCESS_KEY_EMAIL=config('AWS_SECRET_KEY')
AWS_REGION_EMAIL=config('AWS_REGION')

# Digital Ocean Space Cred
AWS_ACCESS_KEY_ID = config('DO_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = config('DO_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'vc-thumbnails'
AWS_S3_ENDPOINT_URL = 'https://blr1.digitaloceanspaces.com'

AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = 'public-read'
AWS_LOCATION = 'studentpeeps'

DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

MEDIA_URL = f"{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/{AWS_LOCATION}/"


# ZeptoMail (secondary SMTP)
ZEPTO_SMTP = {
    "HOST": config("ZEPTO_SMTP_HOST"),
    "PORT": 587,
    "USER": config("ZEPTO_EMAIL_USERNAME"),
    "PASSWORD": config("ZEPTO_EMAIL_PASSWORD"),
    "USE_TLS": True,
    "USE_SSL": False,
}


# Woohoo API Config
WOOHOO_BASE_URL = "https://sandbox.woohoo.in"
WOOHOO_CLIENT_ID = config("WOOHOO_CLIENT_ID")
WOOHOO_CLIENT_SECRET = config("WOOHOO_CLIENT_SECRET")
WOOHOO_USERNAME = config("WOOHOO_USERNAME")
WOOHOO_PASSWORD = config("WOOHOO_PASSWORD")

# Payment Gateway Config
# Active gateway: one of the keys in giftcard/payments/registry.py
# Switch between "razorpay" and "payu" here — no other change needed
ACTIVE_PAYMENT_GATEWAY = "payu"

# Razorpay (disabled but kept for easy switching)
RAZORPAY_KEY_ID     = config("RAZORPAY_KEY_ID")
RAZORPAY_KEY_SECRET = config("RAZORPAY_KEY_SECRET")

# PayU India
PAYU_MERCHANT_KEY  = config("PAYU_MERCHANT_KEY")
PAYU_MERCHANT_SALT = config("PAYU_MERCHANT_SALT")
PAYU_USE_TEST      = True   # Set False for production