# Generated by Django 4.2.21 on 2025-05-15 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='firstname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='lastname',
        ),
    ]
